// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RECMS.Data;

#nullable disable

namespace RECMS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230108111451_3")]
    partial class _3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RECMS.Models.Testing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hobby")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Testings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hobby = "Soccer",
                            Name = "Fantasma"
                        },
                        new
                        {
                            Id = 2,
                            Hobby = "Witch-hunting",
                            Name = "Diablo"
                        },
                        new
                        {
                            Id = 3,
                            Hobby = "Haunting",
                            Name = "Ghost"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
